// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAXHWBFrDbGCopj1sFil_ghLF4AhvyjMY',
    appId: '1:752735753760:web:db3202d84cb124dcd88e45',
    messagingSenderId: '752735753760',
    projectId: 'smart-149a2',
    authDomain: 'smart-149a2.firebaseapp.com',
    storageBucket: 'smart-149a2.firebasestorage.app',
    measurementId: 'G-RFT9XP0RL3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChaBulsU7QaCRkSpGh1hmR2oVoDW6J31U',
    appId: '1:752735753760:android:60a77499cdf24ebbd88e45',
    messagingSenderId: '752735753760',
    projectId: 'smart-149a2',
    storageBucket: 'smart-149a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9_vnAksGpqxEjLMcFAkE8eim8aJi0uCg',
    appId: '1:752735753760:ios:15e37a2daadb9f7ed88e45',
    messagingSenderId: '752735753760',
    projectId: 'smart-149a2',
    storageBucket: 'smart-149a2.firebasestorage.app',
    iosClientId: '752735753760-kgfo2oava48poha742l6srjfqbjtp7cn.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartCanteenOrderingSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9_vnAksGpqxEjLMcFAkE8eim8aJi0uCg',
    appId: '1:752735753760:ios:15e37a2daadb9f7ed88e45',
    messagingSenderId: '752735753760',
    projectId: 'smart-149a2',
    storageBucket: 'smart-149a2.firebasestorage.app',
    iosClientId: '752735753760-kgfo2oava48poha742l6srjfqbjtp7cn.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartCanteenOrderingSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAXHWBFrDbGCopj1sFil_ghLF4AhvyjMY',
    appId: '1:752735753760:web:6866668a3dcabc88d88e45',
    messagingSenderId: '752735753760',
    projectId: 'smart-149a2',
    authDomain: 'smart-149a2.firebaseapp.com',
    storageBucket: 'smart-149a2.firebasestorage.app',
    measurementId: 'G-EEM2JLZ99M',
  );
}
